
2022-12-06 10:00:47,082 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
2022-12-06 10:01:00,229 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
2022-12-06 10:08:32,550 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
2022-12-06 10:08:43,549 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
2022-12-06 10:09:19,078 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
2022-12-06 10:09:21,772 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
2022-12-06 10:10:16,238 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
2022-12-06 11:21:10,842 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
2022-12-06 11:21:29,833 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
2022-12-06 11:22:49,481 ERROR libqtile manager.py:process_key_event():L407 KB command error reload_config: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/command/interface.py", line 312, in call
    return SUCCESS, cmd(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 280, in cmd_reload_config
    self.load_config()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 118, in load_config
    self.dgroups = DGroups(self, self.config.groups, self.config.dgroups_key_binder)
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 89, in __init__
    self._setup_groups()
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 122, in _setup_groups
    self.add_dgroup(group, group.init)
AttributeError: 'str' object has no attribute 'init'

2022-12-06 11:22:49,482 ERROR libqtile hook.py:fire():L406 Error in hook client_killed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 251, in _del
    logger.debug("Deleting %s in %ss", group, self.delay)
AttributeError: 'DGroups' object has no attribute 'delay'
2022-12-06 11:23:05,476 ERROR libqtile core.py:__init__():L103 not starting; existing window manager LG3D
2022-12-06 11:23:10,196 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-12-06 11:23:12,713 ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 198, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 223, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 118, in load_config
    self.dgroups = DGroups(self, self.config.groups, self.config.dgroups_key_binder)
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 89, in __init__
    self._setup_groups()
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 122, in _setup_groups
    self.add_dgroup(group, group.init)
AttributeError: 'str' object has no attribute 'init'
2022-12-06 11:24:44,462 ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 198, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 223, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 118, in load_config
    self.dgroups = DGroups(self, self.config.groups, self.config.dgroups_key_binder)
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 89, in __init__
    self._setup_groups()
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 122, in _setup_groups
    self.add_dgroup(group, group.init)
AttributeError: 'str' object has no attribute 'init'
2022-12-06 11:26:33,563 ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 198, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 223, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 118, in load_config
    self.dgroups = DGroups(self, self.config.groups, self.config.dgroups_key_binder)
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 89, in __init__
    self._setup_groups()
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 122, in _setup_groups
    self.add_dgroup(group, group.init)
AttributeError: 'str' object has no attribute 'init'
2022-12-06 11:27:09,411 ERROR libqtile start.py:start():L92 Qtile crashed
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/scripts/start.py", line 90, in start
    q.loop()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 198, in loop
    asyncio.run(self.async_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 223, in async_loop
    self.load_config(initial=True)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 118, in load_config
    self.dgroups = DGroups(self, self.config.groups, self.config.dgroups_key_binder)
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 89, in __init__
    self._setup_groups()
  File "/usr/lib/python3.10/site-packages/libqtile/dgroups.py", line 122, in _setup_groups
    self.add_dgroup(group, group.init)
AttributeError: 'str' object has no attribute 'init'
2022-12-06 11:35:36,409 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
2022-12-06 11:35:36,438 ERROR libqtile hook.py:fire():L406 Error in hook startup_once
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/home/jasonw/.config/qtile/config.py", line 142, in my_startup_once
    subprocess.Popen([script])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/jasonw/.config/qtile/startup_once.sh'
2022-12-06 11:36:20,627 WARNING libqtile lifecycle.py:_atexit():L37 Qtile will now terminate
2022-12-06 11:36:23,255 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
2022-12-06 11:36:23,269 ERROR libqtile hook.py:fire():L406 Error in hook startup_once
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/hook.py", line 404, in fire
    i(*args, **kwargs)
  File "/home/jasonw/.config/qtile/config.py", line 142, in my_startup_once
    subprocess.Popen([script])
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/jasonw/.config/qtile/startup_once.sh'
2022-12-06 11:37:51,332 WARNING libqtile notify.py:_configure():L90 You must install dbus-next to use the Notify widget.
